name: nsidc_projections
channels:
 - conda-forge
 - default
dependencies:
 - python ~=3.10

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 - jupyterlab
 - matplotlib
 - cartopy
 - pyproj
 - rasterio
 - gdal
 - affine
 - xarray
 - rioxarray
 - h5netcdf
 - pytest
 
